name: task_trackr
description: "Application for tracking your tasks and writong off time."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher_round.png"

dependencies:
  blur: ^4.0.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  get_it: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  shared_preferences: ^2.3.2
  smooth_corner: ^1.1.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF-Pro
      fonts:
      - asset: assets/fonts/SFProText-Regular.ttf
        weight: 400
      - asset: assets/fonts/SFProText-Light.ttf
        weight: 300
      - asset: assets/fonts/SFProText-Medium.ttf
        weight: 500
      - asset: assets/fonts/SFProText-Semibold.ttf
        weight: 600
      - asset: assets/fonts/SFProText-Bold.ttf
        weight: 700
      - asset: assets/fonts/SFProText-Heavy.ttf
        weight: 800
  assets:
    - lib/core/server_token.env
